/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vargas_tamayo_datastruc_proj2;

import java.util.Scanner;
import javax.swing.JOptionPane;

/*
Class name: MainGUI();

Class Author: Luis E. Vargas Tamayo

Purpose of the class: Creates a GUI for the user to interact. 
The program will create 1000 random integers and the user input will be searched to see if a match is found

Date:  9/17/2017

List of changes with dates: none

Special Notes:  The recursion is found on the Recursion Class, in the RecursionPop() method.

*/ 
public class MainGUI extends javax.swing.JFrame {

    Recursion linkMaker= new Recursion();

    /*
    Method Name:  
    Purpose:  
    Parameter:  
    Method Input: 
    Return Value: 
    Date: 9/17/2017
    */
    public MainGUI() 
    {
        initComponents();
    }
       
    /*
    Method Name: RandomNumberMaker500()
    Purpose:  creates 500 random generated numbers and puts them on a link list
    Parameter: none
    Method Input: none
    Return Value: none
    Date: 9/17/2017
    */
    private void RandomNumberMaker500()
    { 
        for(int i = 0; i<500;i++) // iterates 500 times
        {
            double RandomNumber = Math.random()*10000+1; // creates a number between 1 to 10000
                    
            int returner = (int)RandomNumber; // value is converted to an integer

            linkMaker.push(returner); // puts number on the linkList
        }   
    }
      
    /*
    Method Name: isNumeric()
    Purpose:  validates if a String is numberic or not
    Parameter: String
    Method Input:  none
    Return Value: boolean
    Date: 8/28/2017
    */
    private boolean isNumeric(String term)
    {
        int intInteger=0; // default value of variable
        boolean blnKey = true; // boolean controller
        
        try // will try to parse the String to an Integer
        {
            intInteger = Integer.parseInt(term);
        } 
        catch(NumberFormatException ex) // if string is not an integer, the return will be false
        {
            blnKey = false;
            JOptionPane.showMessageDialog(null,"Please Enter A numeric Number between 1-10000 inclusive");
            
            
            
        }
       
        return blnKey;
    }
    
    /*
    Method Name: MainProgram()
    Purpose: runs the entire program  
    Parameter: none  
    Method Input: isNumeric(),RandomNumberMaker()
    Return Value: 
    Date: 9/17/2017
    */
    private void MainProgram()
    { 
        String response = txtUserInput.getText(); // sets the retreive input from user to variable response
        
        if(isNumeric(response)) // if response is a numeric String, then run code
        {
            if(Integer.parseInt(response)>=1  &&  Integer.parseInt(response)<=10000) // if response was between 1 to 100000, then run code
            {
                RandomNumberMaker500(); // creates 500 random generated numbers
                linkMaker.recursionPop(linkMaker.getHead(),Integer.parseInt(response)); // goes through list as recursion to search for user input
            }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Enter A numeric Number between 1-10000 inclusive");
        } 
            
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUserInput = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        txtTitleLabel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        txtUserInput.setFont(new java.awt.Font("Tahoma", 2, 25)); // NOI18N
        txtUserInput.setText("Enter Integer Value");
        txtUserInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserInputMouseClicked(evt);
            }
        });

        btnEnter.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        txtTitleLabel.setEditable(false);
        txtTitleLabel.setBackground(new java.awt.Color(204, 204, 204));
        txtTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTitleLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitleLabel.setText("Is my Number in the random generated numbers?");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 153, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 25)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Enter Numeric Value:\nbetween 1-10000");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserInput, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(211, 211, 211))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(txtTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUserInput, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    /*
    Method Name:btnEnterActionPerformed
    Purpose:  initiate the program
    Parameter:java.awt.event.ActionEvent evt  
    Method Input: MainProgram
    Return Value: none
    Date: 9/17/2017
    */
    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed

        MainProgram(); // runs program
        
    }//GEN-LAST:event_btnEnterActionPerformed
 
    /*
    Method Name: txtUserInputMouseClicked
    Purpose: clears text
    Parameter: java.awt.event.ActionEvent evt
    Method Input: none
    Return Value: none
    Date: 9/17/2017
    */
    private void txtUserInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserInputMouseClicked
        txtUserInput.setText("");
    }//GEN-LAST:event_txtUserInputMouseClicked


    
    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtTitleLabel;
    private javax.swing.JTextField txtUserInput;
    // End of variables declaration//GEN-END:variables
}
