/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import javax.swing.JOptionPane;



public class MainGUI extends javax.swing.JFrame 
{
    TL_Tree arbol = new TL_Tree();


    
    public MainGUI() {initComponents();}
    
    /*
    Method Name: isNumeric()
    Purpose: Check if string is numeric, 
    Parameter: String
    Method Input:  none
    Return Value: boolean
    Date:  9/7/2017
    */   
    private boolean isNumeric(String term)
    {
        int intInteger=0; // default value of variable
        boolean blnKey = true; // boolean controller
        
        try // will try to parse the String to an Integer
        {
            intInteger = Integer.parseInt(term);
        } 
        catch(NumberFormatException ex) // if string is not an integer, the return will be false
        {
            blnKey = false;   
        }
       
        return blnKey;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNumNodes = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tri-Link Demo");

        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(75, 50));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.setPreferredSize(new java.awt.Dimension(75, 50));
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(75, 50));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNumNodes.setText("Number of Nodes");
        btnNumNodes.setPreferredSize(new java.awt.Dimension(75, 50));
        btnNumNodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumNodesActionPerformed(evt);
            }
        });

        btnPrint.setText("Print");
        btnPrint.setMinimumSize(new java.awt.Dimension(75, 50));
        btnPrint.setPreferredSize(new java.awt.Dimension(75, 50));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(btnNumNodes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNumNodes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        try
        {
            String userInput = JOptionPane.showInputDialog(null, "Enter an Integer");
            
            if(isNumeric(userInput))
            {
                arbol.insert(Integer.parseInt(userInput));
            }         
            else if(userInput.isEmpty())
            {}
            else
            {
                JOptionPane.showMessageDialog(null,"ERROR: Enter Numeric Value Only");
            }
        }
        catch(NullPointerException NE)
        {}
        


        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
       
        try
        {
            if(arbol.getRoot() != null)
            {        
                String userInput = JOptionPane.showInputDialog(null, "Enter an Integer");
            
               if(isNumeric(userInput))
               {
                    if(arbol.find(Integer.parseInt(userInput)) == true)
                    {
                       JOptionPane.showMessageDialog(null, "Number is found in tree!");
                    }    
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Number is not found in tree!");
                    } 
                } 
                else if(userInput.isEmpty())
                {}   
                else
                {
                    JOptionPane.showMessageDialog(null,"ERROR: Enter Numeric Value Only");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No Data in the Tree");
            }
        }
        catch(Exception NE)
        {}
        
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnNumNodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumNodesActionPerformed

        if(arbol.getRoot()!= null)
        {
            JOptionPane.showMessageDialog(null,arbol.NodeCount());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No Data in the Tree");
        }

    }//GEN-LAST:event_btnNumNodesActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       
        try
        {
        
            if(arbol.getRoot()!= null)
            {    
               String userInput = JOptionPane.showInputDialog(null, "Enter an Integer you want to Delete");
               
                if(isNumeric(userInput))
                {
                    arbol.Delete(Integer.parseInt(userInput));
                }
                else if(userInput.isEmpty())
                {}
            else
            {
                JOptionPane.showMessageDialog(null,"ERROR: Enter Numeric Value Only");
            }

            }
            else
            {
                JOptionPane.showMessageDialog(null, "No Data in the Tree");
            }
        
        }
        catch(NullPointerException NE)
        {}
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        
        if(arbol.getRoot()!= null)
        {
            JOptionPane.showMessageDialog(null,arbol.Print());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No Data in the Tree");
        }
        
    }//GEN-LAST:event_btnPrintActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNumNodes;
    private javax.swing.JButton btnPrint;
    // End of variables declaration//GEN-END:variables
}
